# This is config file for sourcery, just run `sourcery` in this folder
sources:
  - ../../../../../core/Tests
templates:
  - .sourcery.LinuxMain.stencil
output:
  LinuxMain.swift
args:
  testimports: '@testable import BreezeCoreTests'
